// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesGridSplitLarge from "@/components/sections/features/FeaturesGridSplitLarge";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
              <FeaturesGridSplitLarge
        textAnimation="fade-blur"
        tag="Catering & Events"
        title="Host Your Event or Order Catering with Dhall Dairy & Bakery"
        description="From intimate gatherings to full-scale catering, we bring fresh dairy delights, artisanal breads, and sweets to your events."
        topItems={[{"imageSrc":"https://images.unsplash.com/photo-1517433670267-08bbd4be890f?auto=format&fit=crop&q=80&w=800","description":"Book our space or order fresh dairy platters and bakery spreads for birthdays, celebrations, and gatherings.","title":"Private Events & Parties"},{"title":"Bakery & Dairy Catering","description":"Let us cater fresh milk products, artisanal breads, sweets, and pastries for your next special occasion.","imageSrc":"https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&q=80&w=800"}]}
        bottomItem={{"primaryButton":{"href":"#contact","text":"Get in Touch"},"title":"Custom Orders & Gift Boxes","imageSrc":"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=800","description":"Work with our team to customize sweet boxes, cake designs, and fresh dairy gift baskets for any occasion."}}
      />
            </div>
  );
}
