// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardBrandFloatingCards from "@/components/sections/hero/HeroBillboardBrandFloatingCards";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroBillboardBrandFloatingCards
        textAnimation="fade-blur"
        brand="Dhall Dairy & Bakery"
        description="Fresh farm milk, artisanal cheeses, rich butter, and handcrafted bakery items made daily. Quality dairy products and fresh oven bakes delivered to your table."
        primaryButton={{ text: "Order Now", href: "#order" }}
        secondaryButton={{ text: "View Menu", href: "#menu" }}
        videoSrc="https://storage.googleapis.com/webild/default/templates/joes-coffee/hero/hero.mp4"
        floatingCards={[{"name":"Fresh Milk","imageSrc":"https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800"},{"name":"Artisan Bread","imageSrc":"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800"}]}
      />
            </div>
  );
}
