// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import FeaturesFilterGrid from "@/components/sections/features/FeaturesFilterGrid";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
              <FeaturesFilterGrid
        textAnimation="fade-blur"
        tag="Our Fresh Offerings"
        title="Explore Our Dairy & Bakery Menu"
        description="Farm-fresh milk, pure desi ghee, artisan breads, custom cakes, and traditional sweets made daily."
        categories={["Dairy Products","Fresh Bakes","Sweets & Desserts"]}
        items={[{"name":"Fresh Milk","imageSrc":"https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=800","category":"Dairy Products"},{"imageSrc":"https://images.unsplash.com/photo-1631379578550-7038263db699?auto=format&fit=crop&q=80&w=800","name":"Fresh Cottage Cheese (Paneer)","category":"Dairy Products"},{"name":"Pure Desi Ghee & Butter","category":"Dairy Products","imageSrc":"https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800"},{"category":"Dairy Products","imageSrc":"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800","name":"Fresh Dahi (Yogurt)"},{"category":"Fresh Bakes","name":"Artisan Bread & Buns","imageSrc":"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3IwZkkibx9pPCWCYxzLuBkTZGDO/uploaded-1790783667972-20rjpqdn.jpg","category":"Fresh Bakes","name":"Fresh Chocolate Drip Cake"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3IwZkkibx9pPCWCYxzLuBkTZGDO/uploaded-1790783667970-oimihpka.jpg","category":"Fresh Bakes","name":"Custom Vintage Car Cake"},{"name":"Elegant Butterfly Bow Cake","category":"Fresh Bakes","imageSrc":"https://storage.googleapis.com/webild/users/user_3IwZkkibx9pPCWCYxzLuBkTZGDO/uploaded-1790783667973-alkutv5v.jpg"},{"category":"Sweets & Desserts","name":"Kids Birthday Theme Cake","imageSrc":"https://storage.googleapis.com/webild/users/user_3IwZkkibx9pPCWCYxzLuBkTZGDO/uploaded-1790783667973-39l6mioj.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3IwZkkibx9pPCWCYxzLuBkTZGDO/uploaded-1790783667974-vk049wlp.jpg","name":"Designer Doll & Party Cakes","category":"Sweets & Desserts"}]}
      />
            </div>
  );
}
